language: python

matrix:
  include:
    - python: "3.7"
    - python: "3.8"
      after_script:
        - bash <(curl -s https://codecov.io/bash)

      before_deploy:
        - git stash --all
        - sed -i "s/@@version@@/${TRAVIS_TAG}/g" setup.py

      deploy:
        skip_cleanup: true

        provider: pypi
        user: __token__
        password:
          secure: lsZkMHxTGaOFdL1+jI3CIiaK9UVdbeIr8JgweKOaAVPtFwDYkSwz7HjTGtMjO+obuG3jHuFyfz4yu4OFrh579pxZluwy82qMPjqfo8uycDHs9CHhaWD/J6dx11dBRX0VRPXkM7uR2o/sGuHH3829/iw20udUlzjEJ3lTQoAtPb6uqBNIC7lLItUIey1p9dGZLJD3+NoiKXScvipPQiwYlCPkUxdtv5li$
        on:
          tags: true


install:
  - pip install coverage
  - python setup.py install

script:
  - python runtests.py
