language: python
matrix:
  include:
  - python: '3.7'
  - python: '3.8'
    after_script:
    - bash <(curl -s https://codecov.io/bash)
install:
- pip install coverage
- python setup.py install
script:
- python runtests.py
before_deploy:
- git stash --all
- sed -i "s/@@version@@/${TRAVIS_TAG}/g" setup.py
deploy:
  skip_cleanup: true
  provider: pypi
  user: __token__
  password:
    secure: PQDjEg9YvPlUsrKqEIzHGLFbp5JviYilWxx8VE+4JI7P4LJBeRBETKzLnpoi7V2Y5qe7hyCaN+D5nMzP5UWSlfHfkcNBAKxWTqXG86ZtG7H0pxMjPXStXfDdwcj01yC6IUYdEF9nGbMiYXMmOOxxEpMIbIKPK9XdaGgQnbvF44PTYyQYwr2N4Ry/iGru/uemjqsOwkuKKpL4KootwZh+Hc0xixZWQpp2tN0xJVVw3BOn2bJFR41DD4j6sWJKQ0Z2sD9UjLLT/RNRqiS4knzlRwlOpbmTFofPFxnXQSXf784N3o0QP0JlRfzwayHSGhY/CDw4axch7njrbX6hEn8YOtd/KLcgE4XbgUJ/Wr1qWu8AcOlmL0BJ1eH8NA21FQqO0J3iy62dn2Gk34hZ16tASnPE5lgrT9nj4LV7CgGjkYoEw4WQLKNrVKzdImRgdtKCzAT3aT5JAwhKE2JQlh+yahFFP1JYDlI8e1E76PFBWdQxuqeV4lYIAm2jr6fYglntJVsguZjae2P3N5fgSDUAyrQSvi8SRAPLOQqNV1eGTJe5TQ6LwlD46NrY7jy1AN9dEHUjvyQruqGlC7zQI/scI/S7lm8x3zeVvzt+X6sHwPG2OEzkx9vrCPo9rvHd2yrX1KPHQEIh7EVdMR+n7kQQnD3/71UctuXz3t6DvuPvPM0=
  on:
    python: '3.8'
    tags: true
